services:
  spark-java:
    image: "service:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 40s
    networks:
        dvd-net:
          ipv4_address: 192.168.0.10
    depends_on: 
      mysql: 
        condition: service_healthy
                     
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 40s
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
        reservations:
          cpus: '1.0'
          memory: 2048M
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: "dvd"
      MYSQL_USER: "felfired"
      MYSQL_PASSWORD: "admin_root"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
       dvd-net:
         ipv4_address: 192.168.0.11

networks:
  dvd-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
volumes:
  mysql: {}